CREATE TABLE [dbo].[TBProduct]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [NOME] VARCHAR(50) NOT NULL, 
    [PRECO_VENDA] DECIMAL(7, 2) NOT NULL, 
    [PRECO_CUSTO] DECIMAL(7, 2) NOT NULL, 
    [DISPONIBILIDADE] INT NOT NULL, 
    [DATA_FAB] DATETIME NOT NULL, 
    [DATA_VAL] DATETIME NOT NULL
)
