CREATE TABLE [dbo].[TBSale]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [PRODUTO_ID] INT NOT NULL, 
    [CLIENTE] VARCHAR(50) NOT NULL, 
    [QUANTIDADE] INT NOT NULL, 
    [LUCRO] DECIMAL(9, 2) NOT NULL, 
    CONSTRAINT [FK_TBSale_ToTable] FOREIGN KEY ([PRODUTO_ID]) REFERENCES [TBProduct]([ID])
)
